### ISSUE TITLE
Update Fleet color theme

### ISSUE THREAD

**Issue by OljaKli** [feraxhp/.fleet#1]
Hello,

We’ve noticed that you're creating a color theme for Fleet. The following instructions might help you:
[Building Custom Theme Plugins](https://www.jetbrains.com/help/fleet/building-custom-theme-plugins.html) 
[Modifying Theme Settings](https://www.jetbrains.com/help/fleet/modifying-theme-settings.html) 

Please ensure that you are not using any of the old, edited themes as a reference. Kindly delete the old theme from the folder and create a new one using the latest version of Fleet.

Thank you.

**Comment by feraxhp** [comment]
Actually, I will get rid of it, because this repository is for my personal configuration purpose, but now that fleet change the way the theme is stored I don't need that directory anymore. However thanks for your advice.
